import AddRounded from "@mui/icons-material/AddRounded";
import DeleteOutlineRounded from "@mui/icons-material/DeleteOutlineRounded";
import DescriptionRounded from "@mui/icons-material/DescriptionRounded";
import SendRounded from "@mui/icons-material/SendRounded";
import { Alert, Box, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Drawer, IconButton, List, ListItem, ListItemButton, ListItemText, Stack, TextField, Typography } from "@mui/material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, type KeyboardEvent, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import rehypeSanitize from "rehype-sanitize";
import remarkGfm from "remark-gfm";
import { ApiError } from "../api/client";
import { DocumentsPanel } from "../documents/DocumentsPanel";
import { WorkspaceShell } from "../layouts/WorkspaceShell";
import { conversationKeys, deleteConversation, getConversation, getConversations, streamChat } from "./api";
import type { ChatMessage, ConversationSummary, Source } from "./types";

interface LocalMessage extends ChatMessage { sourcesReady?: boolean }
function SourceDisclosure({ sources }: { sources: Source[] }) { return <details><summary>Sources ({sources.length})</summary><Stack spacing={2} sx={{ mt: 2 }}>{sources.map((source) => <Box key={source.chunk_id} sx={{ borderLeft: 3, borderColor: "primary.main", bgcolor: "action.hover", p: 3 }}><Typography component="p" variant="subtitle2">{source.document_name}</Typography><Typography component="p" variant="body2" color="text.secondary" sx={{ mt: 1 }}>Text excerpt: {source.snippet}</Typography></Box>)}</Stack></details>; }
function MessageContent({ message }: { message: LocalMessage }) { const assistant = message.role === "assistant"; return <Box sx={{ alignSelf: message.role === "user" ? "flex-end" : "flex-start", maxWidth: "min(760px, 92%)", bgcolor: message.role === "user" ? "primary.main" : "background.paper", color: message.role === "user" ? "primary.contrastText" : "text.primary", border: assistant ? 1 : 0, borderColor: "divider", p: 3 }}>{assistant && !message.content && message.status === "streaming" ? <Stack direction="row" spacing={2} sx={{ alignItems: "center" }} aria-live="polite"><CircularProgress size={16} /><Typography>Thinking...</Typography></Stack> : <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{ a: ({ ...props }) => <a {...props} target="_blank" rel="noopener noreferrer" /> }}>{message.content}</ReactMarkdown>}{message.status === "failed" ? <Typography role="status" variant="body2" color="error" sx={{ mt: 2 }}>Response interrupted.</Typography> : null}{message.sourcesReady && message.sources?.length ? <Box sx={{ mt: 3 }}><SourceDisclosure sources={message.sources} /></Box> : null}</Box>; }
function ConversationList({ conversations, activeId, disabled, onNew, onSelect, onDelete }: { conversations?: ConversationSummary[]; activeId: string | null; disabled: boolean; onNew: () => void; onSelect: (id: string) => void; onDelete: (item: ConversationSummary) => void }) { return <Stack sx={{ height: "100%" }}><Box sx={{ p: 3 }}><Button fullWidth variant="contained" startIcon={<AddRounded />} onClick={onNew} disabled={disabled}>New conversation</Button></Box><Divider /><List aria-label="Conversations" sx={{ overflowY: "auto", py: 1 }}>{conversations?.map((item) => <ListItem key={item.conversation_id} disablePadding secondaryAction={<IconButton aria-label={`Delete ${item.title}`} onClick={() => onDelete(item)} disabled={disabled}><DeleteOutlineRounded /></IconButton>}><ListItemButton selected={activeId === item.conversation_id} onClick={() => onSelect(item.conversation_id)} disabled={disabled}><ListItemText primary={item.title} secondary={[item.last_message_preview, conversationTimestamp(item)].filter(Boolean).join(" | ")} /></ListItemButton></ListItem>)}</List></Stack>; }
function isNearBottom(element: HTMLDivElement) { return element.scrollHeight - element.scrollTop - element.clientHeight < 120; }
function conversationTimestamp(item: ConversationSummary) { return [item.created_at && `Created: ${new Date(item.created_at).toLocaleString()}`, item.updated_at && `Updated: ${new Date(item.updated_at).toLocaleString()}`].filter(Boolean).join(" | "); }

export function ChatWorkspace() {
 const queryClient = useQueryClient(); const [activeId, setActiveId] = useState<string | null>(null); const [draft, setDraft] = useState(""); const [localMessages, setLocalMessages] = useState<LocalMessage[] | null>(null); const [streaming, setStreaming] = useState(false); const [error, setError] = useState<string | null>(null); const [drawerOpen, setDrawerOpen] = useState(false); const [documentsOpen, setDocumentsOpen] = useState(false); const [deleteTarget, setDeleteTarget] = useState<ConversationSummary | null>(null); const streamController = useRef<AbortController | null>(null); const transcriptRef = useRef<HTMLDivElement | null>(null); const shouldAutoScroll = useRef(true);
 const conversations = useQuery({ queryKey: conversationKeys.all, queryFn: getConversations }); const history = useQuery({ queryKey: activeId ? conversationKeys.detail(activeId) : ["conversation", "new"], queryFn: () => getConversation(activeId!), enabled: Boolean(activeId) }); const messages = localMessages ?? history.data?.messages ?? [];
 useEffect(() => () => streamController.current?.abort(), []); useEffect(() => { if (shouldAutoScroll.current) if (transcriptRef.current?.scrollTo) transcriptRef.current.scrollTo({ top: transcriptRef.current.scrollHeight }); }, [messages]);
 const deleteMutation = useMutation({ mutationFn: deleteConversation, onSuccess: async (_, id) => { if (id === activeId) { setActiveId(null); setLocalMessages(null); } setDeleteTarget(null); await queryClient.invalidateQueries({ queryKey: conversationKeys.all }); }, onError: (caught) => setError(caught instanceof Error ? caught.message : "Unable to delete the conversation.") });
 const resetToNewConversation = () => { if (!streaming) { setActiveId(null); setLocalMessages(null); setDraft(""); setError(null); setDrawerOpen(false); } }; const selectConversation = (id: string) => { if (!streaming && id !== activeId) { setActiveId(id); setLocalMessages(null); setError(null); setDrawerOpen(false); } };
 async function reconcileAfterFailure(conversationId: string | null, question: string) { await queryClient.invalidateQueries({ queryKey: conversationKeys.all }); if (!conversationId) { setError("The connection ended before the conversation could be confirmed. Check the latest conversation before sending again."); return; } const result = await queryClient.fetchQuery({ queryKey: conversationKeys.detail(conversationId), queryFn: () => getConversation(conversationId) }); const userIndex = result.messages.map((message) => message.role === "user" && message.content === question).lastIndexOf(true); const hasSavedAnswer = result.messages.slice(userIndex + 1).some((message) => message.role === "assistant"); if (hasSavedAnswer) { setLocalMessages(result.messages.map((message) => ({ ...message, sourcesReady: message.role === "assistant" }))); setError("The connection ended, but the saved answer was restored."); } else if (userIndex === -1) setDraft(question); else setError("The question may have been saved. Sending it again could create a duplicate message."); }
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const question = draft.trim(); if (!question || streaming) return; const selectedId = activeId; let confirmedId = selectedId; const previousMessages = messages; const controller = new AbortController(); streamController.current = controller; setDraft(""); setError(null); setStreaming(true); setLocalMessages([...previousMessages, { role: "user", content: question }, { role: "assistant", content: "", status: "streaming" }]); try { await streamChat(question, selectedId, (event) => { if (event.type === "conversation") { confirmedId = event.conversation_id; setActiveId(event.conversation_id); void queryClient.invalidateQueries({ queryKey: conversationKeys.all }); return; } if (event.type === "token") setLocalMessages((items) => items?.map((item, index) => index === items.length - 1 ? { ...item, content: item.content + event.text, status: "streaming" } : item) ?? items); if (event.type === "sources") setLocalMessages((items) => items?.map((item, index) => index === items.length - 1 ? { ...item, sources: event.sources } : item) ?? items); if (event.type === "done") setLocalMessages((items) => items?.map((item, index) => index === items.length - 1 ? { ...item, status: undefined, sourcesReady: true } : item) ?? items); if (event.type === "error") setError(event.message); }, controller.signal); await queryClient.invalidateQueries({ queryKey: conversationKeys.all }); if (confirmedId) await queryClient.invalidateQueries({ queryKey: conversationKeys.detail(confirmedId) }); } catch (caught) { if (controller.signal.aborted) return; const apiError = caught instanceof ApiError ? caught : null; if (apiError && [401, 404, 422].includes(apiError.status)) { setLocalMessages(previousMessages); setDraft(question); if (apiError.status === 404) { setActiveId(null); await queryClient.invalidateQueries({ queryKey: conversationKeys.all }); } setError(apiError.message); } else { setLocalMessages((items) => items?.map((item, index) => index === items.length - 1 ? { ...item, status: "failed" } : item) ?? items); setError(caught instanceof Error ? caught.message : "The response was interrupted."); await reconcileAfterFailure(confirmedId, question); } } finally { if (streamController.current === controller) streamController.current = null; setStreaming(false); } }
 function handleComposerKeyDown(event: KeyboardEvent<HTMLDivElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.closest("form")?.requestSubmit(); } }
 const sidebar = <ConversationList conversations={conversations.data?.conversations} activeId={activeId} disabled={streaming} onNew={resetToNewConversation} onSelect={selectConversation} onDelete={setDeleteTarget} />; const title = activeId ? history.data?.title ?? "Conversation" : "New conversation";
 return <WorkspaceShell title={title} sidebar={sidebar} onOpenConversations={() => setDrawerOpen(true)} toolbarAction={<IconButton aria-label="Open documents" onClick={() => setDocumentsOpen(true)}><DescriptionRounded /></IconButton>}><Drawer open={drawerOpen} onClose={() => setDrawerOpen(false)} slotProps={{ paper: { sx: { width: 304, maxWidth: "85vw" } } }}>{sidebar}</Drawer><Box sx={{ width: "100%", maxWidth: 920, height: "100%", minHeight: 0, display: "flex", flexDirection: "column" }}>{error ? <Alert severity="error" role="alert" sx={{ m: 3, mb: 0 }} onClose={() => setError(null)}>{error}</Alert> : null}{conversations.isError ? <Alert severity="warning" sx={{ m: 3, mb: 0 }} action={<Button color="inherit" size="small" onClick={() => void conversations.refetch()}>Retry</Button>}>Unable to load conversations.</Alert> : null}<Stack ref={transcriptRef} spacing={3} sx={{ flex: 1, overflowY: "auto", p: { xs: 3, sm: 5 } }} onScroll={(event) => { shouldAutoScroll.current = isNearBottom(event.currentTarget); }}>{history.isLoading ? <Stack sx={{ alignItems: "center", pt: 8 }}><CircularProgress aria-label="Loading conversation" /></Stack> : null}{!activeId && !messages.length ? <Stack spacing={2} sx={{ alignItems: "center", pt: 12, textAlign: "center" }}><Typography variant="h2">No conversation selected</Typography><Typography color="text.secondary">Start a conversation or choose one from the list.</Typography></Stack> : null}{history.isError ? <Alert severity="error" action={<Button color="inherit" size="small" onClick={() => void history.refetch()}>Retry</Button>}>Unable to load this conversation.</Alert> : null}{messages.map((message, index) => <MessageContent key={`${message.role}-${index}`} message={message} />)}</Stack><Box component="form" onSubmit={(event) => void submit(event)} sx={{ p: { xs: 3, sm: 4 }, borderTop: 1, borderColor: "divider" }}><Stack direction="row" spacing={2} sx={{ alignItems: "flex-end" }}><TextField fullWidth placeholder="Ask about your documents" slotProps={{ htmlInput: { "aria-label": "Question" } }} multiline maxRows={6} value={draft} disabled={streaming} onChange={(event) => setDraft(event.target.value)} onKeyDown={handleComposerKeyDown} /><IconButton type="submit" color="primary" aria-label="Send message" disabled={streaming || !draft.trim()}><SendRounded /></IconButton></Stack></Box></Box><DocumentsPanel open={documentsOpen} onClose={() => setDocumentsOpen(false)} /><Dialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)}><DialogTitle>Delete conversation?</DialogTitle><DialogContent><Typography>{deleteTarget?.title} and its messages cannot be restored.</Typography></DialogContent><DialogActions><Button onClick={() => setDeleteTarget(null)}>Cancel</Button><Button color="error" onClick={() => deleteTarget && deleteMutation.mutate(deleteTarget.conversation_id)} disabled={deleteMutation.isPending}>Delete</Button></DialogActions></Dialog></WorkspaceShell>;
}
